# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de Giro',
                'verbose_name_plural': 'Categorías de Giro',
            },
        ),
        migrations.CreateModel(
            name='ClaseGiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Clase de Giro',
                'verbose_name_plural': 'Clases de Giro',
            },
        ),
        migrations.CreateModel(
            name='Giro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('afecto_iva', models.NullBooleanField(default=True)),
                ('categoria_tributaria', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', 'ND')], max_length=1, verbose_name='Categoría Tributaria')),
                ('disponible_internet', models.BooleanField(default=True)),
                ('categoria_giro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giros', to='girocomercial.CategoriaGiro')),
            ],
            options={
                'verbose_name': 'Giro Comercial',
                'verbose_name_plural': 'Giros Comerciales',
            },
        ),
        migrations.AddField(
            model_name='categoriagiro',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='girocomercial.ClaseGiro'),
        ),
    ]
