# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 04:40
from __future__ import unicode_literals

from django.db import migrations
import fixturemigration.operations

class Migration(migrations.Migration):

    dependencies = [
        ('girocomercial', '0001_initial'),
    ]

    operations = [
        fixturemigration.operations.LoadFixtureMigration(
            fixturemigration='apps/girocomercial/fixtures/initial_data.json'
        )
    ]
